namespace WebGameServer.Core.World;

public enum BlockType : ushort
{
    Air = 0,
    Stone = 1,
    Dirt = 2,
    Grass = 3,
    Water = 4,
    Sand = 5,
    Wood = 6,
    Leaves = 7,
    Glass = 8,
    Brick = 9,
    OreIron = 10,
    Coal = 11,
    Bedrock = 12,
    Snow = 13,
    Ice = 14,
    Lava = 15,
    Torch = 16,
    Ladder = 17,
    Fence = 18,
    DoorWood = 19,
    Chest = 20,
    CraftingTable = 21,
    Furnace = 22,
    OreGold = 23,
    OreDiamond = 24,
    Planks = 25,
    Cobblestone = 26,
    StoneBrick = 27,
    WoolWhite = 28,
    WoolRed = 29,
    WoolBlue = 30,
    WoolGreen = 31,
    Bookshelf = 32,
}
